# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2ab9309e2d227f9deabb7c33b54423e0ca38b0a0fd0346ac9b5a38cb691c2045e288c3afc7a0d18c5daceeea86ec43c3bc836062bdc2c8599fe257ac8abe8c3

test:
  secret_key_base: 8b047f76435176901949136daf0e63177255544172faa0acddc003ef0bd78cbfa26d8e1eabec56934bf5c4b50861d35b7fa0f74bf153d6c02b8b75c27472e89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
